@endpoint = http://127.0.0.1:3030

GET {{endpoint}} HTTP/1.1

###

GET {{endpoint}}/login HTTP/1.1


###

POST {{endpoint}}/login HTTP/1.1
content-Type: application/json

{
    "usercode": "company",
    "email": "dw@dw.ac.kr",
    "password": "dw1234"
}


###

POST {{endpoint}}/login HTTP/1.1
content-Type: application/json

{
    "usercode": "customer",
    "email": "dw@dw.ac.kr",
    "password": "dw1234"
}


###


POST {{endpoint}}/login HTTP/1.1
content-Type: application/json

{
    "usercode": "admin",
    "email": "dw@dw.ac.kr",
    "password": "dw1234"
}


###
POST {{endpoint}}/register HTTP/1.1
content-Type: application/json

{
    "email": "hj@hj.ac.kr",
    "password": "hj123",
    "name": "hj",
    "phone": "010-1234-5678",
    "address": "kwdorm"
}

###

GET  {{endpoint}}/mypage HTTP/1.1
